### PR TITLE
Make billy compliant with, and switch to, Scrapelib 1.x

### PR DESCRIPTION
**Pull request by mileswwatkins**
Open States scrapers have already been made compliant.

### CODE REVIEW

**Comment by rshorey** [comment]
I'll check this one locally.

**Comment by rshorey** [comment]
I installed requirements.txt and ran some samples locally, and they worked. @mileswwatkins anything else you think I ought to check? If not, happy to merge.

**Comment by mileswwatkins** [comment]
Nah, I've been on this `billy` branch for yesterday and today, and haven't had anything break while running local scrapes. Go for the merge!

**Comment by rshorey** [comment]
ok!

**Pull request merged**
